//! Drift detection: is the committed markdown still true?
//!
//! Generated documentation rots the moment someone lands a change without
//! regenerating, and stale documentation is worse than none because an agent
//! will believe it. The check exists so CI can fail on that, and so a developer
//! can find out before review rather than after.
//!
//! Four distinct kinds of staleness, kept separate because the fixes differ:
//!
//! - **Content drift** — a source file changed since its card was generated.
//!   Fix: regenerate.
//! - **Removed** — a card whose source file no longer exists. Fix: regenerate,
//!   which prunes it (unless it carries notes).
//! - **Coverage** — an indexed source file with no card at all, usually a file
//!   added since the last generation. Fix: regenerate.
//! - **Index drift** — the graph was built by a different extractor than the
//!   one that produced the markdown. Fix: reindex, then regenerate, because
//!   regenerating alone would embed results from an outdated extractor.
//!
//! The check reads the manifest rather than regenerating and diffing, so it is
//! cheap enough to run on every commit.

use std::collections::BTreeSet;
use std::path::Path;

use crate::graph::types::GraphV1;
use crate::markdown::manifest::Manifest;
use crate::markdown::{write, MANIFEST_FILE};

#[derive(Debug, Default, Clone, PartialEq, Eq)]
pub struct DriftReport {
    /// Sources whose content changed since their card was generated.
    pub content_drift: Vec<String>,
    /// Cards whose source file is gone.
    pub removed: Vec<String>,
    /// Indexed sources with no card.
    pub coverage: Vec<String>,
    /// Set when the markdown predates the current extractor.
    pub index_drift: Option<String>,
    /// Set when no manifest exists at all.
    pub missing: bool,
}

impl DriftReport {
    /// Whether anything needs regenerating.
    pub fn is_clean(&self) -> bool {
        !self.missing
            && self.content_drift.is_empty()
            && self.removed.is_empty()
            && self.coverage.is_empty()
            && self.index_drift.is_none()
    }

    pub fn total(&self) -> usize {
        self.content_drift.len() + self.removed.len() + self.coverage.len()
    }
}

/// Compare the on-disk markdown against a freshly built graph.
pub fn check(repo_root: &Path, graph: &GraphV1) -> DriftReport {
    let Some(manifest) = load_manifest(repo_root) else {
        return DriftReport {
            missing: true,
            ..DriftReport::default()
        };
    };

    let mut report = DriftReport::default();

    // An extractor change invalidates every card at once, so report it as one
    // finding rather than as drift on every file.
    if manifest.extractor != graph.extractor {
        report.index_drift = Some(format!(
            "markdown generated by {}, graph built by {}",
            manifest.extractor, graph.extractor
        ));
    }

    let live: BTreeSet<&str> = graph.files.iter().map(|f| f.path.as_str()).collect();

    for entry in &manifest.entries {
        let Some(source) = entry.source.as_deref() else {
            continue;
        };

        let Some(file) = graph.files.iter().find(|f| f.path == source) else {
            report.removed.push(source.to_string());
            continue;
        };

        if entry.source_hash.as_deref() != Some(file.hash.as_str()) {
            report.content_drift.push(source.to_string());
        }
    }

    let covered: BTreeSet<&str> = manifest.covered_sources().into_iter().collect();
    for source in live.difference(&covered) {
        report.coverage.push((*source).to_string());
    }

    report.content_drift.sort();
    report.removed.sort();
    report.coverage.sort();
    report
}

fn load_manifest(repo_root: &Path) -> Option<Manifest> {
    let path = write::markdown_dir(repo_root).join(MANIFEST_FILE);
    let raw = std::fs::read_to_string(path).ok()?;
    serde_json::from_str(&raw).ok()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::graph::types::FileEntryV1;

    fn graph_with(files: &[(&str, &str)], extractor: &str) -> GraphV1 {
        let mut g = GraphV1::new("repo", extractor);
        for (path, hash) in files {
            g.files.push(FileEntryV1 {
                path: (*path).to_string(),
                hash: (*hash).to_string(),
                size: 1,
                language: "typescript".to_string(),
                node_count: 1,
            });
        }
        g.normalize();
        g
    }

    fn generated(files: &[(&str, &str)]) -> (tempfile::TempDir, GraphV1) {
        let repo = tempfile::tempdir().expect("tempdir");
        let graph = graph_with(files, "test");
        write::write_all(repo.path(), &graph).expect("write");
        (repo, graph)
    }

    #[test]
    fn freshly_generated_markdown_is_clean() {
        let (repo, graph) = generated(&[("src/a.ts", "h1")]);

        let report = check(repo.path(), &graph);

        assert!(report.is_clean(), "unexpected drift: {report:?}");
    }

    #[test]
    fn a_changed_source_file_is_content_drift() {
        let (repo, _) = generated(&[("src/a.ts", "h1")]);

        let report = check(repo.path(), &graph_with(&[("src/a.ts", "h2")], "test"));

        assert_eq!(report.content_drift, vec!["src/a.ts"]);
        assert!(!report.is_clean());
    }

    #[test]
    fn a_deleted_source_file_is_reported_as_removed() {
        let (repo, _) = generated(&[("src/a.ts", "h1"), ("src/b.ts", "h1")]);

        let report = check(repo.path(), &graph_with(&[("src/a.ts", "h1")], "test"));

        assert_eq!(report.removed, vec!["src/b.ts"]);
    }

    #[test]
    fn a_new_source_file_is_a_coverage_gap() {
        let (repo, _) = generated(&[("src/a.ts", "h1")]);

        let report = check(
            repo.path(),
            &graph_with(&[("src/a.ts", "h1"), ("src/new.ts", "h1")], "test"),
        );

        assert_eq!(report.coverage, vec!["src/new.ts"]);
    }

    /// One finding, not one per file: an extractor change invalidates
    /// everything, and listing every card would bury the actual instruction.
    #[test]
    fn an_extractor_change_is_reported_once() {
        let (repo, _) = generated(&[("src/a.ts", "h1"), ("src/b.ts", "h1")]);

        let report = check(repo.path(), &graph_with(&[("src/a.ts", "h1")], "different"));

        assert!(report.index_drift.is_some());
        assert!(report.index_drift.expect("drift").contains("different"));
    }

    #[test]
    fn missing_markdown_is_reported_as_missing_not_clean() {
        let repo = tempfile::tempdir().expect("tempdir");

        let report = check(repo.path(), &graph_with(&[("src/a.ts", "h1")], "test"));

        assert!(report.missing);
        assert!(!report.is_clean());
    }

    #[test]
    fn a_corrupt_manifest_reads_as_missing() {
        let (repo, graph) = generated(&[("src/a.ts", "h1")]);
        let path = write::markdown_dir(repo.path()).join(MANIFEST_FILE);
        std::fs::write(path, "{ not json").expect("corrupt");

        assert!(check(repo.path(), &graph).missing);
    }

    /// Editing notes changes the file but not the generated block, and
    /// reporting that as drift would train people to ignore the check.
    #[test]
    fn editing_notes_does_not_register_as_drift() {
        let (repo, graph) = generated(&[("src/a.ts", "h1")]);
        let card = write::markdown_dir(repo.path()).join("src-a-ts.md");
        let annotated = std::fs::read_to_string(&card)
            .expect("read")
            .replace("## Notes", "## Notes\n\nHand-written context.");
        std::fs::write(&card, annotated).expect("annotate");

        assert!(check(repo.path(), &graph).is_clean());
    }

    #[test]
    fn several_kinds_of_drift_are_reported_together() {
        let (repo, _) = generated(&[("src/a.ts", "h1"), ("src/gone.ts", "h1")]);

        let report = check(
            repo.path(),
            &graph_with(&[("src/a.ts", "changed"), ("src/new.ts", "h1")], "test"),
        );

        assert_eq!(report.content_drift, vec!["src/a.ts"]);
        assert_eq!(report.removed, vec!["src/gone.ts"]);
        assert_eq!(report.coverage, vec!["src/new.ts"]);
        assert_eq!(report.total(), 3);
    }

    #[test]
    fn regenerating_clears_every_kind_of_drift() {
        let (repo, _) = generated(&[("src/a.ts", "h1"), ("src/gone.ts", "h1")]);
        let updated = graph_with(&[("src/a.ts", "changed"), ("src/new.ts", "h1")], "test");

        assert!(!check(repo.path(), &updated).is_clean());
        write::write_all(repo.path(), &updated).expect("regenerate");

        assert!(check(repo.path(), &updated).is_clean());
    }

    #[test]
    fn findings_are_sorted_for_stable_output() {
        let (repo, _) = generated(&[("src/b.ts", "h1"), ("src/a.ts", "h1")]);

        let report = check(repo.path(), &graph_with(&[], "test"));

        assert_eq!(report.removed, vec!["src/a.ts", "src/b.ts"]);
    }
}
