//! `.forgemap` manifest reading and writing — line-based, no YAML library.
//!
//! Implements FORGEMAP.md §13: regex extraction for reads, fixed render order for writes,
//! rolling window for `agent_sessions:`, verbatim preservation of `cross_cutting_patterns:`.

use std::path::Path;

use anyhow::{Context, Result};
use lazy_static::lazy_static;
use regex::Regex;

use super::constants::SESSIONS_WINDOW;
use super::inject::safe_write_file;
use super::types::ExistingManifest;

lazy_static! {
    static ref RE_PROJECT: Regex = Regex::new(r"(?m)^project:\s*(.+)$").unwrap();
    static ref RE_DESCRIPTION: Regex = Regex::new(r#"(?m)^description:\s*"?(.+?)"?\s*$"#).unwrap();
    static ref RE_MODE: Regex = Regex::new(r"(?m)^mode:\s*(\w+)").unwrap();
}

/// Read an existing `.forgemap` manifest, extracting preserved fields.
pub fn read_existing_manifest(abs_path: &Path) -> Result<ExistingManifest> {
    let content = std::fs::read_to_string(abs_path)
        .with_context(|| format!("Cannot read manifest: {}", abs_path.display()))?;

    let project = RE_PROJECT
        .captures(&content)
        .map(|c| c[1].trim().to_string())
        .unwrap_or_default();

    let description = RE_DESCRIPTION
        .captures(&content)
        .map(|c| c[1].trim().to_string())
        .unwrap_or_default();

    let mode = RE_MODE
        .captures(&content)
        .map(|c| c[1].trim().to_string())
        .unwrap_or_else(|| "semi".to_string());

    // Extract agent_sessions block (from marker to EOF or next top-level key).
    let agent_sessions_block = extract_block(&content, "agent_sessions:");

    // Extract cross_cutting_patterns block.
    let cross_cutting_block = extract_block(&content, "cross_cutting_patterns:");

    Ok(ExistingManifest {
        project,
        description,
        mode,
        agent_sessions_block,
        cross_cutting_block,
    })
}

/// Extract a YAML-like block from marker to the next unindented key or EOF.
fn extract_block(content: &str, marker: &str) -> String {
    let lines: Vec<&str> = content.lines().collect();
    let start = match lines
        .iter()
        .position(|l| l.trim_start() == marker || l.starts_with(marker))
    {
        Some(i) => i,
        None => return String::new(),
    };

    let mut end = start + 1;
    while end < lines.len() {
        let line = lines[end];
        // Next top-level key (not indented, ends with `:`) signals end of block.
        if !line.is_empty()
            && !line.starts_with(' ')
            && !line.starts_with('\t')
            && line != marker
            && !line.starts_with('#')
        {
            break;
        }
        end += 1;
    }

    lines[start..end].join("\n")
}

/// Options for writing a manifest.
pub struct WriteManifestOpts<'a> {
    pub abs_path: &'a Path,
    pub project: &'a str,
    pub description: &'a str,
    pub mode: &'a str,
    pub packages: &'a std::collections::BTreeMap<String, super::types::PackageManifestEntry>,
    pub cross_cutting_block: &'a str,
    pub agent_sessions_block: &'a str,
    pub dry_run: bool,
}

/// Write (or preview) a `.forgemap` manifest.
pub fn write_manifest(opts: &WriteManifestOpts<'_>) -> Result<String> {
    let mut out = String::new();

    out.push_str(
        "# .forgemap — ForgeMap project manifest (auto-generated by `tok forgemap manifest`)\n",
    );
    out.push_str(&format!("project: {}\n", opts.project));
    out.push_str(&format!("description: \"{}\"\n", opts.description));
    out.push_str(&format!("mode: {}\n", opts.mode));
    out.push('\n');

    // Packages.
    out.push_str("packages:\n");
    for (key, entry) in opts.packages {
        let display_key = if key.is_empty() {
            "/".to_string()
        } else if key.ends_with('/') {
            key.clone()
        } else {
            format!("{}/", key)
        };
        out.push_str(&format!("  {}:\n", display_key));
        out.push_str(&format!("    purpose: \"{}\"\n", entry.purpose));
        out.push_str(&format!(
            "    key_files: [{}]\n",
            entry.key_files.join(", ")
        ));
        out.push_str(&format!(
            "    depends_on: [{}]\n",
            entry.depends_on.join(", ")
        ));
        out.push('\n');
    }

    // Cross-cutting patterns (preserved verbatim).
    if !opts.cross_cutting_block.is_empty() {
        out.push_str(opts.cross_cutting_block);
        out.push('\n');
    } else {
        out.push_str("cross_cutting_patterns: {}\n");
    }
    out.push('\n');

    // Agent sessions with rolling window.
    let sessions_block = apply_sessions_window(opts.agent_sessions_block);
    if !sessions_block.is_empty() {
        out.push_str(&sessions_block);
        out.push('\n');
    } else {
        out.push_str("agent_sessions:\n");
    }

    if !opts.dry_run {
        safe_write_file(opts.abs_path, &out)
            .with_context(|| format!("Failed to write manifest: {}", opts.abs_path.display()))?;
    }

    Ok(out)
}

/// Apply rolling window: keep only the last `SESSIONS_WINDOW` entries.
fn apply_sessions_window(block: &str) -> String {
    if block.is_empty() {
        return String::new();
    }

    let marker = "  - agent:";
    let parts: Vec<&str> = block.split(marker).collect();

    if parts.len() <= 1 {
        return block.to_string();
    }

    // parts[0] is the "agent_sessions:" header line.
    let header = parts[0];
    let entries: Vec<&str> = parts[1..].to_vec();

    if entries.len() <= SESSIONS_WINDOW {
        return block.to_string();
    }

    // Keep trailing SESSIONS_WINDOW entries.
    let keep = &entries[entries.len() - SESSIONS_WINDOW..];
    let mut result = header.to_string();
    for entry in keep {
        result.push_str(marker);
        result.push_str(entry);
    }

    result
}

/// Detect project metadata from `package.json` or `Cargo.toml`.
pub fn detect_project_meta(repo_root: &Path) -> (String, String) {
    // Try package.json first.
    let pkg_json = repo_root.join("package.json");
    if pkg_json.exists() {
        if let Ok(content) = std::fs::read_to_string(&pkg_json) {
            if let Ok(val) = serde_json::from_str::<serde_json::Value>(&content) {
                let name = val
                    .get("name")
                    .and_then(|v| v.as_str())
                    .map(|n| {
                        // Strip org scope: @org/foo → foo.
                        n.rsplit('/').next().unwrap_or(n).to_string()
                    })
                    .unwrap_or_default();
                let desc = val
                    .get("description")
                    .and_then(|v| v.as_str())
                    .unwrap_or("")
                    .to_string();
                if !name.is_empty() {
                    return (name, desc);
                }
            }
        }
    }

    // Try Cargo.toml.
    let cargo_toml = repo_root.join("Cargo.toml");
    if cargo_toml.exists() {
        if let Ok(content) = std::fs::read_to_string(&cargo_toml) {
            if let Ok(val) = content.parse::<toml::Value>() {
                let name = val
                    .get("package")
                    .and_then(|p| p.get("name"))
                    .and_then(|v| v.as_str())
                    .unwrap_or("")
                    .to_string();
                let desc = val
                    .get("package")
                    .and_then(|p| p.get("description"))
                    .and_then(|v| v.as_str())
                    .unwrap_or("")
                    .to_string();
                if !name.is_empty() {
                    return (name, desc);
                }
            }
        }
    }

    // Fallback: directory name.
    let dir_name = repo_root
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("project")
        .to_string();

    (dir_name, String::new())
}
