//! Obsidian wiki generation — per-file pages with wikilinks, bootstrap index, and sync.
//!
//! Implements FORGEMAP.md §14: `render_file_page`, `bootstrap_wiki`, `sync_wiki`.

use std::collections::BTreeMap;
use std::path::Path;

use anyhow::{Context, Result};

use super::constants::SKIP_DIRS;
use super::inject::safe_write_file;
use super::types::{FileInfo, ParsedHeader, RelPath};

const AGENT_NOTES_MARKER: &str =
    "<!-- AGENT NOTES · edits below survive `tok forgemap wiki bootstrap` -->";
const AUTO_GEN_MARKER: &str =
    "<!-- AUTO-GENERATED by `tok forgemap wiki` · edits above AGENT NOTES will be overwritten -->";

/// Render a single file's wiki page.
pub fn render_file_page(rel: &str, header: &ParsedHeader) -> String {
    let mut out = String::new();

    out.push_str(AUTO_GEN_MARKER);
    out.push_str("\n\n");
    out.push_str(&format!("# {}\n\n", rel));
    out.push_str(&format!("> {}\n\n", header.first_line));

    // Exports.
    out.push_str("## Exports\n\n");
    if header.exports.is_empty() || header.exports.trim().to_lowercase() == "none" {
        out.push_str("_none_\n");
    } else {
        for exp in header.exports.split('|') {
            let trimmed = exp.trim();
            if !trimmed.is_empty() {
                out.push_str(&format!("- `{}`\n", trimmed));
            }
        }
    }
    out.push('\n');

    // Used by.
    out.push_str("## Used by\n\n");
    if header.used_by.is_empty() || header.used_by.trim().to_lowercase() == "none" {
        out.push_str("_none_\n");
    } else {
        for line in header.used_by.lines() {
            let trimmed = line.trim();
            if trimmed.is_empty() {
                continue;
            }
            // Convert to wikilink: src/api/routes.ts → [[src/api/routes|src/api/routes.ts]]
            let parts: Vec<&str> = trimmed.splitn(2, '→').collect();
            let file_part = parts[0].trim();
            let sym_part = parts.get(1).map(|s| s.trim()).unwrap_or("");

            if is_placeholder(file_part) {
                out.push_str(&format!("- `{}`", file_part));
            } else {
                let wikilink = to_wikilink(file_part);
                out.push_str(&format!("- {}", wikilink));
            }
            if !sym_part.is_empty() {
                out.push_str(&format!(" → {}", sym_part));
            }
            out.push('\n');
        }
    }
    out.push('\n');

    // Related (optional).
    if let Some(ref related) = header.related {
        if !related.is_empty() {
            out.push_str("## Related\n\n");
            for line in related.lines() {
                let trimmed = line.trim();
                if !trimmed.is_empty() {
                    out.push_str(&format!("- {}\n", trimmed));
                }
            }
            out.push('\n');
        }
    }

    // Wiki link (optional).
    if let Some(ref wiki) = header.wiki {
        if !wiki.is_empty() {
            out.push_str("## Extended documentation\n\n");
            out.push_str(&format!("See: {}\n\n", wiki));
        }
    }

    // Rules.
    out.push_str("## Rules\n\n");
    if header.rules.is_empty() || header.rules.trim().to_lowercase() == "none" {
        out.push_str("_none_\n");
    } else {
        // Escape inline wikilinks in rules text.
        let escaped = escape_wikilinks(&header.rules);
        out.push_str(&escaped);
        out.push('\n');
    }
    out.push('\n');

    // Agent history.
    out.push_str("## Agent history\n\n");
    if header.agent.is_empty() {
        out.push_str("_none_\n");
    } else {
        for line in header.agent.lines() {
            let trimmed = line.trim();
            if !trimmed.is_empty() {
                out.push_str(&format!("- `{}`\n", trimmed));
            }
        }
    }
    out.push('\n');

    // Messages (optional).
    if let Some(ref msg) = header.message {
        if !msg.is_empty() {
            out.push_str("## Open messages\n\n");
            out.push_str(&format!("{}\n\n", msg));
        }
    }

    out.push_str(AGENT_NOTES_MARKER);
    out.push('\n');

    out
}

/// Bootstrap a wiki vault: one page per annotated file, plus README.md and log.md.
pub fn bootstrap_wiki(
    infos: &BTreeMap<RelPath, FileInfo>,
    out_dir: &Path,
    _repo_root: &Path,
) -> Result<(usize, usize)> {
    let mut written = 0usize;
    let mut skipped = 0usize;

    std::fs::create_dir_all(out_dir)
        .with_context(|| format!("Cannot create wiki dir: {}", out_dir.display()))?;

    for (rel, info) in infos {
        let header = match &info.header {
            Some(h) => h,
            None => {
                skipped += 1;
                continue;
            }
        };

        let page = render_file_page(rel, header);

        // Output path: strip extension, add .md.
        let out_rel = Path::new(rel).with_extension("md");
        let out_path = out_dir.join(&out_rel);

        // Preserve AGENT NOTES from existing page if it exists.
        let final_content = if out_path.exists() {
            merge_agent_notes(&page, &out_path)
        } else {
            page
        };

        if let Some(parent) = out_path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        safe_write_file(&out_path, &final_content)?;
        written += 1;
    }

    // Emit README.md (index grouped by top-level directory).
    let readme = build_wiki_readme(infos);
    safe_write_file(&out_dir.join("README.md"), &readme)?;

    // Emit log.md (manifest contents if available).
    let log = build_wiki_log(_repo_root);
    safe_write_file(&out_dir.join("log.md"), &log)?;

    Ok((written, skipped))
}

/// Generate a single narrative project wiki.
pub fn sync_wiki(repo_root: &Path, out_path: &Path) -> Result<()> {
    let dirs = enumerate_top_dirs(repo_root, 8);

    let mut content = String::new();
    content.push_str(AUTO_GEN_MARKER);
    content.push_str("\n\n");
    content.push_str("# Project Wiki\n\n");

    content.push_str("## 1. Identity\n\n");
    content.push_str("_TODO: Project name, purpose, team, constraints._\n\n");

    content.push_str("## 2. L0 Mapping\n\n");
    content.push_str("Top-level directories:\n\n");
    for d in &dirs {
        content.push_str(&format!("- `{}/`\n", d));
    }
    content.push('\n');

    content.push_str("## 3. Semantic Topology\n\n");
    content.push_str("_TODO: Key data flows, domain boundaries._\n\n");

    content.push_str("## 4. Operational Workflows\n\n");
    content.push_str("_TODO: Build, deploy, CI/CD notes._\n\n");

    content.push_str("## 5. Testing\n\n");
    content.push_str("_TODO: Testing strategy, coverage targets._\n\n");

    content.push_str("## 6. Hotspots\n\n");
    content.push_str("_TODO: Known fragile areas, tech debt._\n\n");

    content.push_str("## 7. Refresh Protocol\n\n");
    content.push_str("Run `tok forgemap refresh <path>` to update structural fields.\n");
    content.push_str("Run `tok forgemap wiki sync` to regenerate this page.\n\n");

    content.push_str(AGENT_NOTES_MARKER);
    content.push('\n');

    // Preserve existing AGENT NOTES if file exists.
    let final_content = if out_path.exists() {
        merge_agent_notes(&content, out_path)
    } else {
        content
    };

    if let Some(parent) = out_path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    safe_write_file(out_path, &final_content)?;

    Ok(())
}

// ── Helpers ──

fn to_wikilink(path: &str) -> String {
    let stripped = path.trim();
    let no_ext = Path::new(stripped)
        .with_extension("")
        .to_string_lossy()
        .replace('\\', "/");
    format!("[[{}|{}]]", no_ext, stripped)
}

fn is_placeholder(value: &str) -> bool {
    let lower = value.trim().to_lowercase();
    lower.starts_with("none")
        || lower.starts_with("n/a")
        || lower.starts_with("tbd")
        || lower.starts_with("todo")
}

fn escape_wikilinks(text: &str) -> String {
    text.replace("[[", "`[[").replace("]]", "]]`")
}

fn merge_agent_notes(new_content: &str, existing_path: &Path) -> String {
    let existing = match std::fs::read_to_string(existing_path) {
        Ok(s) => s,
        Err(_) => return new_content.to_string(),
    };

    // Find AGENT NOTES section in existing file.
    let marker = AGENT_NOTES_MARKER;
    let existing_notes = existing
        .find(marker)
        .map(|pos| &existing[pos + marker.len()..])
        .unwrap_or("");

    // Find marker in new content and replace everything after it.
    match new_content.find(marker) {
        Some(pos) => {
            let mut result = new_content[..pos + marker.len()].to_string();
            result.push_str(existing_notes);
            result
        }
        None => {
            let mut result = new_content.to_string();
            result.push('\n');
            result.push_str(marker);
            result.push_str(existing_notes);
            result
        }
    }
}

fn build_wiki_readme(infos: &BTreeMap<RelPath, FileInfo>) -> String {
    let mut out = String::new();
    out.push_str("# ForgeMap Wiki Index\n\n");

    // Group by top-level directory.
    let mut groups: BTreeMap<String, Vec<&str>> = BTreeMap::new();
    for rel in infos.keys() {
        let top = rel.split('/').next().unwrap_or("root").to_string();
        groups.entry(top).or_default().push(rel);
    }

    for (group, files) in &groups {
        out.push_str(&format!("## {}\n\n", group));
        for f in files {
            let link = Path::new(f).with_extension("md");
            out.push_str(&format!(
                "- [{}]({})\n",
                f,
                link.to_string_lossy().replace('\\', "/")
            ));
        }
        out.push('\n');
    }

    out
}

fn build_wiki_log(repo_root: &Path) -> String {
    let manifest_path = repo_root.join(super::constants::MANIFEST_FILENAME);
    let mut out = String::new();
    out.push_str("# ForgeMap Log\n\n");

    if manifest_path.exists() {
        if let Ok(content) = std::fs::read_to_string(&manifest_path) {
            out.push_str("```yaml\n");
            out.push_str(&content);
            out.push_str("\n```\n");
        } else {
            out.push_str("_Cannot read `.forgemap` manifest._\n");
        }
    } else {
        out.push_str("_No `.forgemap` manifest found. Run `tok forgemap manifest` first._\n");
    }

    out
}

fn enumerate_top_dirs(repo_root: &Path, max: usize) -> Vec<String> {
    let skip: std::collections::HashSet<&str> = SKIP_DIRS.iter().copied().collect();
    let mut dirs = Vec::new();

    if let Ok(entries) = std::fs::read_dir(repo_root) {
        for entry in entries.flatten() {
            if let Ok(ft) = entry.file_type() {
                if ft.is_dir() {
                    let name = entry.file_name().to_string_lossy().to_string();
                    if !name.starts_with('.') && !skip.contains(name.as_str()) {
                        dirs.push(name);
                    }
                }
            }
        }
    }

    dirs.sort();
    dirs.truncate(max);
    dirs
}
